Add dimension, metric and namespace validation
awslabs/aws-embedded-metrics-dotnet pull request #37
Opened 2022-09-07 17:51 UTC by markkuhn

Related to:
* https://github.com/awslabs/aws-embedded-metrics-node/pull/135
* https://github.com/awslabs/aws-embedded-metrics-java/pull/119

*Description of changes:*
Added validation for dimension, metric and namespace

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-09-07 19:04 UTC, amazon-ankalini requested changes

2022-09-07 19:04 UTC, amazon-ankalini commented on tests/Amazon.CloudWatch.EMF.Tests/Model/DimensionSetTests.cs
> +                dimensionSet.AddDimension(new string('a', Constants.MAX_DIMENSION_NAME_LENGTH + 1), "value");
@markkuhn probably will be more readable if you move out the string construction into a separate variable like in another tests

2022-09-08 22:13 UTC, markkuhn commented on src/Amazon.CloudWatch.EMF/Utils/Validator.cs
> +            if (dimensionName == null || dimensionName.Trim().Length == 0)
In what package can I find `isBlank()`?

2022-09-08 22:54 UTC, markkuhn commented on src/Amazon.CloudWatch.EMF/Utils/Validator.cs
> +        internal static void ValidateDimensionSet(string dimensionName, string dimensionValue)
Namespaces cannot contains methods. They can only contains nested namespaces, structs and classes.

2022-09-08 23:21 UTC, markkuhn commented on src/Amazon.CloudWatch.EMF/Utils/Validator.cs
> +        internal static void ValidateDimensionSet(string dimensionName, string dimensionValue)
This is not the case in C#

2022-09-08 23:26 UTC, markkuhn commented on src/Amazon.CloudWatch.EMF/Model/DimensionSet.cs
> +            Validator.ValidateDimensionSet(key, value);
According to [this](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/constructor) page, it is appropriate to throw constructors in C#.

2022-09-08 23:42 UTC, markkuhn commented on src/Amazon.CloudWatch.EMF/Utils/Validator.cs
> +        internal static void ValidateNamespace(string namespaceName)
I've marked them as `readonly` with the `in` keyword.

2022-09-09 00:08 UTC, amazon-ankalini commented on src/Amazon.CloudWatch.EMF/Utils/Validator.cs
> +            if (dimensionName == null || dimensionName.Trim().Length == 0)
@markkuhn in Java package :) Nevermind that

2022-09-09 00:12 UTC, amazon-ankalini approved these changes

2022-09-14 16:09 UTC, Himtanaya approved these changes

2022-09-15 23:11 UTC, merged